version: ' 3.8'

services:
  ms-asientos:
    build: .
    container_name: ms-asientos-container
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-2bd6720e-duocuc-7153.c.aivencloud.com:28226/db_asientos?sslMode=REQUIRED
      - SPRING_DATASOURCE_PASSWORD=aqui_pon_tu_password_local
      - COGNITO_ISSUER_URI=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_WlflzEy7K
    networks:
      - red-cine
networks:
  red-cine:
    driver: bridge