spring.application.name=ms-asientos

server.port=8082

# Configuración de Conexión a AWS RDS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Limita las conexiones simultáneas
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1